include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"
    - android/**

linter:
  rules:
    prefer_single_quotes: true
    require_trailing_commas: true
    always_use_package_imports: true
    avoid_print: true
